apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
data:
  PORT: "5555"
  NODE_ENV: "production"
  MONGO_URI: "mongodb+srv://admin:$(DB_PASSWORD)@devopsdilip.dudrh.mongodb.net/?retryWrites=true&w=majority&appName=DevopsDilip"
