apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
data:
  PORT: "5555"
  MONGO_URI: "mongodb+srv://${DB_USER}:${DB_PASSWORD}@devopsdilip.dudrh.mongodb.net/?retryWrites=true&w=majority&appName=DevopsDilip"
