apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: dilipopseng/hp:latest
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: DB_PASSWORD
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: MONGO_URI
