apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
        - name: my-node-app
          image: dilipopseng/ops
          ports:
            - containerPort: 5555
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: MONGO_URI
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: DB_PASSWORD
